# Modernized Aerospace Configuration
# https://github.com/nikitabobko/aerospace

# Sketchybar integration - update sketchybar when workspace changes
exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

# Start AeroSpace at login (recommended, but you can also use brew services)
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Prevent window resetting when switching workspaces
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

# Window behavior optimizations
automatically-unhide-macos-hidden-apps = false

# Accordion layout padding (helps with window persistence)
accordion-padding = 30

# CRITICAL: Only use Aerospace workspaces, not macOS Spaces
# After switching, windows should stay in their Aerospace workspace layout
# Use Alt+1-6 for Aerospace workspaces (NOT Ctrl+1-6 for macOS Spaces!)

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# Gaps
[gaps]
inner.horizontal = 5
inner.vertical = 5
outer.left = 5
outer.bottom = 5
outer.top = 5
outer.right = 5

# Main mode keybindings
[mode.main.binding]

# === WINDOW NAVIGATION (vim-style) ===
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# === WINDOW MOVEMENT ===
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# === WINDOW RESIZING ===
alt-ctrl-h = 'resize width -50'
alt-ctrl-j = 'resize height +50'
alt-ctrl-k = 'resize height -50'
alt-ctrl-l = 'resize width +50'

# === WINDOW OPERATIONS ===
# Aerospace fullscreen (RECOMMENDED - persists across workspace switches)
alt-f = 'fullscreen'

# macOS native fullscreen (creates separate Space - NOT recommended with Aerospace)
# alt-shift-f = 'macos-native-fullscreen'

# Other window operations
alt-shift-space = 'layout floating tiling' # Toggle float
alt-0 = 'balance-sizes' # Balance window sizes
alt-r = 'flatten-workspace-tree' # Reset layout

# === LAYOUT SWITCHING ===
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout tiles accordion'

# === WORKSPACE SWITCHING ===
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'

# === MOVE WINDOW TO WORKSPACE ===
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'

# === CONFIGURATION ===
alt-shift-r = 'reload-config'

# === APP LAUNCH SHORTCUTS (from your old skhd config) ===
# Code apps
alt-c = 'exec-and-forget open -a "Cursor"'
alt-d = 'exec-and-forget open -a "DataGrip"'

# Web apps
alt-z = 'exec-and-forget open -a "Zen Browser"'
alt-b = 'exec-and-forget open -a "Arc"'

# Terminal
alt-w = 'exec-and-forget open -a "WezTerm"'

# Communication
alt-s = 'exec-and-forget open -a "Superhuman"'
alt-a = 'exec-and-forget open -a "Asana"'
alt-m = 'exec-and-forget open -a "Slack"'
alt-e = 'exec-and-forget open -a "Calendar"'

# Media/Design
alt-g = 'exec-and-forget open -a "Figma"'

# Productivity/Other
alt-i = 'exec-and-forget open -a "TickTick"'
alt-p = 'exec-and-forget open -a "ChatGPT"'
alt-o = 'exec-and-forget open -a "Screenshot"'

# === APPLICATION-SPECIFIC RULES ===
# Only float system utilities, not regular apps
[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.systempreferences'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.Calculator'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.SystemPreferences'
run = 'layout floating'
