# Minimal, fast prompt
format = """
$directory$git_branch$git_status$node$python
$character"""

[directory]
style = "blue bold"
truncation_length = 3
truncate_to_repo = false

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[git_branch]
style = "purple bold"
format = "[$symbol$branch]($style) "

[git_status]
style = "red bold"
format = '([$all_status$ahead_behind]($style) )'
